### ISSUE TITLE
后端配置项没有正常加载，上传插件不能正常使用！

### ISSUE THREAD

**Issue by ewintec** [widuu/qiniu_ueditor_1.4.3#18]
设置后运行index.html  上传图片或文件 提示后端配置项没有正常加载，上传插件不能正常使用！ 环境 kangle+php5.3

**Comment by widuu** [comment]
已经修复代码，请更新成最新的代码

**Comment by ZhanMa** [comment]
后台配置项返回格式出错，上传功能将不能正常使用！
我把php目录下config.json 改成 qiniu的了，php目录下配置config.json没动，不知道这个配置有问题吗

**Comment by widuu** [comment]
一般不会出现错误，您把配置文件发下我看看

**Comment by zonas1991** [comment]
我也是出错。

**Comment by zonas1991** [comment]
后端配置项没有正常加载，上传插件不能正常使用！

**Comment by Jieck2002** [comment]
我也是这个问题

**Comment by widuu** [comment]
直接访问http://网站地址/ueditor文件夹/php/controller.php?action=config 看看报什么错误吗？初始化一般是这个地方出现错误了或者解析json错误

**Comment by widuu** [comment]
确实有问题已经修复，请下载最新版本测试，谢谢反馈问题

**Comment by zonas1991** [comment]
应该是没兼容PHP版本的问题，我换个PHP版本就好了。

**Comment by widuu** [comment]
现在没问题了，我试了下都兼容了，以前的有点小BUG

**Comment by Jieck2002** [comment]
经测试已兼容，https://jieck.cn/templet/blog/article.php?id=112&from=all
