### ISSUE TITLE
http请求错误

### ISSUE THREAD

**Issue by langkejianxin** [widuu/qiniu_ueditor_1.4.3#2]
我按说明配置了七牛，但是还是提示http请求错误，如下图：
![image](https://cloud.githubusercontent.com/assets/8114593/6893171/57107950-d6fd-11e4-8d1b-b25f0e7ec274.png)
 我用chrome看返回错误是：
error: "key doesn't match with scope"

**Comment by widuu** [comment]
稍后更新请下载新版测试

**Comment by widuu** [comment]
请下载测试新版本
