### ISSUE TITLE
远程图片上传 功能有bug吧？？？

### ISSUE THREAD

**Issue by vb3064** [widuu/qiniu_ueditor_1.4.3#20]
远程复制图片功能有bug吧？？？复制第一张没有问题，复制第二张的时候，图片地址错误，无法显示。。
另外能不能实现图片压缩功能呢？

**Comment by widuu** [comment]
这个远程上传有最大执行时间的限制，图片复杂采用的是catchimage 可以将php文件设置set_time_limit(0); 还有一种可能是图片防采集设置，这样七牛就采集不了了
