### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wjlgogo** [widuu/qiniu_ueditor_1.4.3#21]
incorrect region, please use up-z2.qiniu.com

**Comment by widuu** [comment]
这个是七牛服务端报错，就是地区报错，因为空间是华南的，你可以把php/config.json中的 upload.qiniu.com 换成 up-z2.qiniu.com

**Comment by qqq111111** [comment]
还是报错incorrect region, please use up-z2.qiniu.com

"uploadQiniuUrl"   : "http://up-z2.qiniu.com/", /* 七牛上传地址 */和"ChunkUploadQiniuUrl": "http://up-z2.qiniu.com", /* 分片上传创建的host地址 */这两条吗？

**Comment by widuu** [comment]
对的 一般就换这两个地址就没问题的，你也可以看看你的空间属于华南 华北 还是华东区域的

**Comment by wjlgogo** [comment]
是华南地区的，但是还是不行啊！

**Comment by widuu** [comment]
你用我带的demo试着有问题吗，那个是我的帐号，如果还是不行你可以把你的配置信息等发到我的邮箱admin@widuu.com 到时候我给你测试试试

**Comment by widuu** [comment]
` "uploadQiniuUrl"   : "http://up-z2.qiniu.com/", /* 七牛上传地址 */
    "qiniuUploadPath"  : "uploads/",   /* 七牛上传的前缀 */
	"qiniuDatePath"    : "mmdd",       /* 文件夹后的时间例如 uploads/0712 留空uploads/, 格式 yyyy == 2017 yy == 17 mm 月份 07 dd 日期 12 */
	"uploadSaveType"   : "date",       /* 保存文件的名称类型 */
	"getTokenActionName" : "getToken", /* 获取上传token的方法*/
    "removeImageActionName" : "remove",  /* 删除图片的方法 */
    "VideoBlockFileSize" : 4194304,  /* 视频块大小,是每块4MB，所以这个不用修改 */
    "VideoChunkFileSize" : 2097152,  /* 视频上传分块大小，建议是整数倍防止出错，列如1048576（1MB），524288（512KB）默认是2MB */
    "VideoChunkMaxSize"  : 10485760, /* 视频文件超过多大来进行分片上传，现在默认是10MB */
    "ChunkUploadQiniuUrl": "http://up-z2.qiniu.com", /* 分片上传创建的host地址 */`

测试完毕，将两个参数修改了，上传没有问题，我开了个华南的测试了一下

**Comment by HansHHH** [comment]
@widuu 多图上传是没有问题, 但是单图上传还是会报这个错

**Comment by widuu** [comment]
更新浏览器缓存和本地缓存，这个用的是一个http上传接口

**Comment by widuu** [comment]
已修复
