### ISSUE TITLE
多图上传报错

### ISSUE THREAD

**Issue by saresam** [widuu/qiniu_ueditor_1.4.3#22]
“上传失败，请重试”
![image](https://user-images.githubusercontent.com/30542980/29486177-bd9966b2-8512-11e7-915c-422adcce4674.png)

**Comment by saresam** [comment]
重试还是这样，单独一张图片的上传就没问题

**Comment by widuu** [comment]
请在浏览器控制台查看一下网络请求信息，反馈给我，我好帮您查找问题，我刚才测试没有问题

**Comment by widuu** [comment]
我看您直接issue,如果您们的网站有回调需要重写一下回调方法的
