### ISSUE TITLE
可以升级一下七牛云的驱动吗？现在没法上传到华南

### ISSUE THREAD

**Issue by xiaomeng79** [widuu/qiniu_ueditor_1.4.3#24]
报这个错：incorrect region, please use up-z2.qiniu.com

**Comment by widuu** [comment]
请问你用的直传还是？

**Comment by widuu** [comment]
我本地测试了，华南可以的，请将php/config.json 中的 uploadQiniuUrl 和 ChunkUploadQiniuUrl 修改成 http://up-z2.qiniu.com/ 就可以了

**Comment by xiaomeng79** [comment]
您好！我用的是直传,修改后还是报那个错误，
![11](https://user-images.githubusercontent.com/24215119/29757065-a24ef564-8bdb-11e7-8207-3060871525ed.png)
搜了一下解决方法，我换成华东的可以，https://segmentfault.com/q/1010000008596429

**Comment by widuu** [comment]
你是上传视频吗？？？

**Comment by widuu** [comment]
我开了一个华南的 测试没有问题呀，请问你是测试上传视频还是？？

**Comment by xiaomeng79** [comment]
我是上传图片!就是不行啊，上传到华南后这些地址不是都改变了吗？



![222](https://user-images.githubusercontent.com/24215119/29761536-20596a28-8bfc-11e7-8fd7-802f54a55d57.jpg)

**Comment by widuu** [comment]
URL上传的时候用不到这些参数的，不可能呀 我刚才开的华南的试了一点问题没有呀

**Comment by widuu** [comment]
你可以把你的key 之类的信息发我邮箱 我给你看看哪里的问题
