### ISSUE TITLE
单上传视频或图片还是报错

### ISSUE THREAD

**Issue by Xieyunhu** [widuu/qiniu_ueditor_1.4.3#28]
单上传视频或图片报错，incorrect region, please use up-z1.qiniu.com，但是配置文件我已经改成up-z1.qiniu.com 华北的了，为什么还出现这种情况，多上传图片没问题！

**Comment by widuu** [comment]
配置之后一定要更新浏览器缓存还有本地的缓存

**Comment by Xieyunhu** [comment]
已经弄好了，谢了！

**Comment by Xieyunhu** [comment]
我还想问一下，这个有没有一个功能，就是列出七牛里面的所有视频图片文件，然后可以选择指定图片或视频到编辑器，不好意思我是新人，很多东西都是看的不是很明白！

**Comment by widuu** [comment]
多图上传或者多视频上传里边有个在线列表，那里您可以上传您的信息

**Comment by Xieyunhu** [comment]
图片的没有问题，但是您说的多视频上传，我没有找到这个图标，看了一下UEditor官方文档也是只有单视频上传！所以这个视频的列表，可不可以麻烦你说的再清楚一些！

**Comment by widuu** [comment]
不好意思，说错了，应该是附件管理里边有，可以对视频进行操作管理

**Comment by Xieyunhu** [comment]
谢了 ~_ ~
