### ISSUE TITLE
关于QiniuDriver.class.php的$qiniu_up_host属性值的问题

### ISSUE THREAD

**Issue by mokeyjay** [widuu/qiniu_ueditor_1.4.3#35]
按照README.MD中的指示，我修改了`php/config.json` 中的 `uploadQiniuUrl` 和 `ChunkUploadQiniuUrl` 参数，但是上传依然报错：
`incorrect region, please use up-z2.qiniu.com`

最后经过排查才发现 `QiniuDriver.class.php`的`$qiniu_up_host`属性值被硬编码了，修改为 `http://up-z2.qiniu.com` 后正常

**Comment by widuu** [comment]
谢谢，已经修复
