### ISSUE TITLE
上传文件和视频action一直都是uploadimage，导致文件上传失败。

### ISSUE THREAD

**Issue by LeeAries** [widuu/qiniu_ueditor_1.4.3#36]
上传文件和视频时，action一直是uploadimage，导致文件上传失败。
Request URL:xxxxxxxxxxx/php/controller.php?action=uploadimage&encode=utf-8。
经测试  getActionUrl(action) 会执行两次，第一次action值正确，第二次action会替换为uploadimage。
![image](https://user-images.githubusercontent.com/22006358/37959893-cadc8346-31e6-11e8-94d4-b2c45cf679c6.png)

**Comment by widuu** [comment]
你这个应该是通过php方式上传，不是直传所以会走uploadimage,底层走的是QiniuDriver.class.php uploadFile
