### ISSUE TITLE
七牛远程获取文件接口无法正常工作

### ISSUE THREAD

**Issue by BenzLeung** [widuu/qiniu_ueditor_1.4.3#39]
**一、**

https://github.com/widuu/qiniu_ueditor_1.4.3/blob/c82ed27570621ba4e42fcd18082218b92a0ad042/php/vendor/driver/QiniuDriver.class.php#L15

`http://iovip.qbox.me` 这个域名，七牛有区域限制，例如 `http://iovip-z2.qbox.me` 。建议做个配置项，让我们可以配置区域。并相应改变这个域名值。

**二、**

https://github.com/widuu/qiniu_ueditor_1.4.3/blob/c82ed27570621ba4e42fcd18082218b92a0ad042/php/vendor/driver/QiniuDriver.class.php#L86-L93

七牛远程获取文件接口 `fetchFile()`，这儿的 `$result['error']` 应改成 `$response['error']` ，这个接口内不存在 $result 变量，因此无法返回正确的错误信息，这让我查了好久没查出错误，还以为是目标文件链接防盗链了。

我自己发现了错误二并改了，然后七牛返回错误信息是 `incorrect region` ，才发现了错误一。。。

**Comment by widuu** [comment]
谢谢，已经修改
