### ISSUE TITLE
默认配置php/conf.php中$HOST配置有问题

### ISSUE THREAD

**Issue by yidiandianlan** [widuu/qiniu_ueditor_1.4.3#4]
默认配置`$HOST  = "http://gitwiduu.u.qiniudn.com/";`
如果$HOST 末尾带`/`， 上传七牛之后返回的url 为 `http://gitwiduu.u.qiniudn.com//14304697138.png`
会301定向跳转到 `http://gitwiduu.u.qiniudn.com/14304697138.png`

建议默认配置$HOST末尾不加`/`
如果不加`/` 需要修改php/getTonke.php ，这一部分 `$returnBody = "{\"url\":\"{$host}$(key)`

**Comment by widuu** [comment]
谢谢提出问题，已经修改
